In [14]:
import numpy as np

np.set_printoptions(precision=3)

## Working Example

In [15]:
Q = np.array([
    [ 0.00, -0.80, -0.60],
    [ 0.80, -0.36,  0.48],
    [ 0.60,  0.48, -0.64]
])

D = np.array([
    [9, 0, 0],
    [0, 4, 0],
    [0, 0, 1]
])

A = Q.T @ D @ Q

In [16]:
A

array([[ 2.92 , -0.864,  1.152],
       [-0.864,  6.509,  3.322],
       [ 1.152,  3.322,  4.571]])

In [17]:
np.linalg.eig(A)

(array([ 4.,  1.,  9.]), array([[  8.000e-01,  -6.000e-01,  -3.872e-17],
        [ -3.600e-01,  -4.800e-01,   8.000e-01],
        [  4.800e-01,   6.400e-01,   6.000e-01]]))

## Power Iteration

In [18]:
def power_iteration(A, v=None):
    if v is None:
        v = np.random.normal(size=A.shape[1])
    previous = np.empty(shape=A.shape[1])
    while True:
        previous[:] = v
        v = A @ v
        v = v / np.linalg.norm(v)
        if np.all(np.abs(v - previous) < 0.00001):
            break
    return v

In [19]:
power_iteration(A)

array([ -3.567e-06,   8.000e-01,   6.000e-01])